// Define the mutation types
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_FLIGHTS = 'SET_FLIGHTS'
export const SET_AIRPORTS = 'SET_AIRPORTS'
export const SET_FLIGHT_TO_BOOK = 'SET_FLIGHT_TO_BOOK'
export const SET_PASSENGERS = 'SET_PASSENGERS'
export const CONFIRM_BOOKING = 'CONFIRM_BOOKING'
export const SET_BOOKINGS = 'SET_BOOKINGS'